# Generated by Django 3.2.16 on 2022-10-24 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_veiculo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('chassi', models.CharField(max_length=200)),
                ('renavam', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('ano', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
