# Generated by Django 3.2.16 on 2022-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0005_abastecimento_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='combustivel',
            field=models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('ETANOL', 'ETANOL'), ('DIESEL', 'DIESEL')], default='GASOLINA', max_length=200),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='itens',
            field=models.TextField(),
        ),
    ]
