# Generated by Django 3.2.16 on 2022-10-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0006_auto_20221026_0857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abastecimento',
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
    ]
