# Generated by Django 3.2.16 on 2022-10-26 10:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abastecimento', '0008_delete_veiculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('km', models.FloatField()),
                ('itens', models.TextField()),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.veiculo')),
                ('usuario_de_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(default=datetime.datetime.now)),
                ('km', models.FloatField()),
                ('litros', models.FloatField()),
                ('valor', models.FloatField()),
                ('posto', models.CharField(max_length=200)),
                ('motorista', models.CharField(max_length=200)),
                ('combustivel', models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('ETANOL', 'ETANOL'), ('DIESEL', 'DIESEL')], default='GASOLINA', max_length=200)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.veiculo')),
                ('usuario_de_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
