# Generated by Django 3.2.16 on 2022-10-27 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0011_alter_abastecimento_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='data_abastecimento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data_manutencao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
