# Generated by Django 3.2.16 on 2022-10-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0013_combustivel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='combustivel',
        ),
    ]
