# Generated by Django 3.2.16 on 2022-11-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0015_combustivel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combustivel',
        ),
    ]
