# Generated by Django 3.2.16 on 2022-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0016_delete_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
