# Generated by Django 3.2.16 on 2022-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0017_auto_20221101_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='km',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='litros',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
