# Generated by Django 3.2.16 on 2022-11-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0018_auto_20221101_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='renavam',
        ),
    ]
